sonar.projectKey=its-robermdev_Lab1-Cloud2
sonar.organization=its-robermdev
sonar.projectName=Lab1-Cloud2
sonar.sources=src
sonar.exclusions=**/*.test.js,**/*.spec.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
